### ISSUE TITLE
Allow customization of Mongo connection at the Spider or Item level

### ISSUE THREAD

**Issue by AdamFerguson** [sebdah/scrapy-mongodb#17]
First of all, thanks for the great project. Discovered it last night and pretty much just worked for storing results from a Spider.

I'm using a project that has multiple Spiders storing different items and it would be really helpful if the Mongo connection could be customized to point at a different database/collection depending on the item being stored or the spider being run. Was planning on forking the project and adding myself but am wondering about your thoughts first.

**Comment by thiagof** [comment]
That would make use of the Spider property [`custom_settings`](https://github.com/scrapy/scrapy/search?utf8=%E2%9C%93&q=update_settings)

**Comment by sebdah** [comment]
This has now been released in version 0.9.0. Thanks @thiagof for the pull request.
